version: '3.7'
services:
  rtr:
    container_name: 'free-rtr-static'
    image: 'free-rtr'
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    #command: bash -c "/src/start-static.bash && bash"
    command: bash -c "/src/start-rip.bash && bash"
    #command: bash -c "bash"
    ports: 
      - "2001:2001"
      - "2002:2002"
      - "2003:2003"
      - "2004:2004"
      - "2005:2005"
    environment:
      - directory=/src/rip
      - routern=4
    volumes:
      - ./:/src
    working_dir: /src
